### ISSUE TITLE
TypeError: DB is not a constructor

### ISSUE THREAD

**Issue by Luke1810** [Mephisto5558/Mongoose-DB#3]
In the line `client.db = await new DB().init(process.env.MONGODB_URI, 'saves');`
I get the error  "TypeError: DB is not a constructor". The line is copied from the readme.

**Comment by Mephisto5558** [comment]
Please show the actual code of how you import DB.

**Comment by Luke1810** [comment]
`const { DB } = require('@mephisto5558/mongoose-db');` at the start

```js
 try {
    client.db = await new DB().init(process.env.MONGODB_URI, 'saves');
    console.log('Verbunden');
...
```

**Comment by Mephisto5558** [comment]
Are you sure that that part of your code throws the error? In the most recent version of this library, your code is correct.
Please look a your stack trace again.
Also please show the output of `npm list @mephisto5558/mongoose-db`.

**Comment by Luke1810** [comment]
Error: TypeError: DB is not a constructor
    at main ...\source\index.js:27:23)

**Comment by Mephisto5558** [comment]
Also please show the output of `npm list @mephisto5558/mongoose-db`.

I am unable to reproduce your issue, see my screenshot:
![test](https://github.com/Mephisto5558/Mongoose-DB/assets/87113906/baa692f8-d928-497e-b11d-62893eb4146f)

**Comment by Luke1810** [comment]
solved it alone, still thank you for helping
